import type { Metadata } from 'next';
import { Merriweather } from 'next/font/google';
import './globals.css';
import MuiSetUp from '../common/Mui/MuiSetup';
import Favicon from '../../public/favicon.ico';

const inter = Merriweather({ subsets: ['latin'], weight: ['300', '400', '700'] });

export const metadata: Metadata = {
    title: 'Đồng Khởi Phát',
    description: 'Generated by create next app',
    icons: [{ rel: 'icon', url: Favicon.src }],
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <MuiSetUp>{children}</MuiSetUp>
            </body>
        </html>
    );
}
